apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../ingress-resources/go-app-dev-ingress.yaml

images:
  - name: anuroop21/go-app
    newTag: 86ae82773aedd62aa6ce6990a95ef8efae03a67c
